default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
		ensure_git_status_clean()
		prerelease_tests()
		load_key()
		signing()
		increment_build_number(xcodeproj: "aperture.xcodeproj")
		build()
		upload()
		build_number = get_build_number(
			xcodeproj: "aperture.xcodeproj"
		)
		git_commit(
			path: "./*.*",
			message: "Bump build number to #{build_number}"
		)
		dsym()
  end

	lane :load_key do
		app_store_connect_api_key(
			key_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			issuer_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			key_filepath: "./fastlane/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.p8",
			duration: 1200,
			in_house: false
		)
	end

  lane :signing do
		get_certificates()
		get_provisioning_profile()
  end

	lane :build do
		build_app(
			scheme: "aperture",
			export_options: {
				provisioningProfiles: {
					"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
					"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
				}
			}
		)
	end

	lane :prerelease_tests do
	  run_tests(
			project: "aperture.xcodeproj",
			devices: ["iPhone SE (3rd generation)"],
			scheme: "aperture",
			ensure_devices_found: "true"
		)
	end

  lane :dsym do
		sentry_upload_dsym(
			auth_token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
			org_slug: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
			project_slug: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
			dsym_path: "./aperture.app.dSYM.zip",
			info_plist: "./aperture/Info.plist"
		)
  end
  
  lane :upload do
		load_key()
		upload_to_testflight()
  end
  
end
